#!/bin/bash

# JVM setup
: "${ZOMBOID_JVM_MAX_HEAP:=3072m}"
sed -i "s/-Xmx[0-9]\+[mMgG]\?/-Xmx${ZOMBOID_JVM_MAX_HEAP}/" /server/ProjectZomboid64.json

# Server command-line arguments
: "${ZOMBOID_SERVER_DEBUG:=}"
: "${ZOMBOID_SERVER_DISABLE_LOG:=}"
: "${ZOMBOID_SERVER_DEBUG_LOG:=}"
: "${ZOMBOID_SERVER_NAME:=my-zomboid-server}"
: "${ZOMBOID_SERVER_ADMIN_USERNAME:=admin}"
: "${ZOMBOID_SERVER_PASSWORD:=}"
if [ -z "${ZOMBOID_SERVER_ADMIN_PASSWORD}" ]; then
    ZOMBOID_SERVER_ADMIN_PASSWORD=$(openssl rand -base64 12)
    echo "ZOMBOID_SERVER_ADMIN_PASSWORD not set, generated new password: $ZOMBOID_SERVER_ADMIN_PASSWORD"
fi

: "${ZOMBOID_DISCORD_TOKEN:=}"
: "${ZOMBOID_DISCORD_CHANNEL:=}"
: "${ZOMBOID_DISCORD_CHANNEL_ID:=}"


# Bootstrap the server.ini with settings that can't be overridden or changed at runtime
mkdir -p /game-data/Server
SERVER_INI="/game-data/Server/${ZOMBOID_SERVER_NAME}.ini"
if [ -f "${SERVER_INI}" ]; then
    sed -i "s/^RCONPassword=.*/RCONPassword=${ZOMBOID_SERVER_ADMIN_PASSWORD}/" "${SERVER_INI}"
    sed -i "s/^UPnP=.*/UPnP=false/" "${SERVER_INI}"
    sed -i "s/^Password=.*/Password=${ZOMBOID_SERVER_PASSWORD}/" "${SERVER_INI}"
    sed -i "s/^DiscordEnable=.*/DiscordEnable=${ZOMBOID_DISCORD_TOKEN:+true}/" "${SERVER_INI}"
    sed -i "s/^DiscordToken=.*/DiscordToken=${ZOMBOID_DISCORD_TOKEN}/" "${SERVER_INI}"
    sed -i "s/^DiscordChannel=.*/DiscordChannel=${ZOMBOID_DISCORD_CHANNEL}/" "${SERVER_INI}"
    sed -i "s/^DiscordChannelID=.*/DiscordChannelID=${ZOMBOID_DISCORD_CHANNEL_ID}/" "${SERVER_INI}"
else
    cat > "${SERVER_INI}" << EOF
UPnP=false
RCONPassword=${ZOMBOID_SERVER_ADMIN_PASSWORD}
Password=${ZOMBOID_SERVER_PASSWORD}
DiscordEnable=${ZOMBOID_DISCORD_TOKEN:+true}
DiscordToken=${ZOMBOID_DISCORD_TOKEN}
DiscordChannel=${ZOMBOID_DISCORD_CHANNEL}
DiscordChannelID=${ZOMBOID_DISCORD_CHANNEL_ID}
EOF
fi

# Ensure the mods directory exists to avoid an innocuous error message when the server starts.
mkdir -p /game-data/mods

exec /server/start-server.sh \
    -cachedir="/game-data" \
    -port 16261 \
    -udpport 16262 \
    -steamvac true \
    ${ZOMBOID_SERVER_DEBUG:+-debug} \
    -disablelog="$ZOMBOID_SERVER_DISABLE_LOG" \
    -debuglog="$ZOMBOID_SERVER_DEBUG_LOG" \
    -servername "$ZOMBOID_SERVER_NAME" \
    -adminusername "$ZOMBOID_SERVER_ADMIN_USERNAME" \
    -adminpassword "$ZOMBOID_SERVER_ADMIN_PASSWORD"
