#!/bin/bash

# Get the version from the News_EN.txt file
# The version is the last line that starts with [VERSION], with examples like:
# [VERSION]41.67 and 41.68  -> 41.68
# [VERSION]41.69            -> 41.69
# [VERSION]41.70            -> 41.70
# [VERSION]41.71            -> 41.71
# [VERSION]41.72            -> 41.72
# [VERSION]41.73            -> 41.73
# [VERSION]41.74 - 41.77    -> 41.77
# [VERSION]41.78            -> 41.78
# [VERSION]41.78.11 Hotfix  -> 41.78.11

version=$(grep -i '\[VERSION\]' /server/media/lua/shared/Translate/EN/News_EN.txt | tail -n 1 | sed -E 's/\[VERSION\]//; s/ Hotfix.*//; s/.*and //; s/.* - //; s/ .*//')
echo "$version"
