name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hordehost
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: hordehost/zomboid-server:latest
          cache-from: type=registry,ref=hordehost/zomboid-server:buildcache
          cache-to: type=registry,ref=hordehost/zomboid-server:buildcache,mode=max

      - name: Extract version
        id: version
        run: |
          VERSION=$(docker run --rm --entrypoint /server/version hordehost/zomboid-server:latest)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag with version and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            hordehost/zomboid-server:latest
            hordehost/zomboid-server:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=hordehost/zomboid-server:buildcache
          cache-to: type=registry,ref=hordehost/zomboid-server:buildcache,mode=max
